services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: disparador_dev
    ports:
      - "5433:5432"
    volumes:
<<<<<<< HEAD
<<<<<<< HEAD
      - pgdata:/var/lib/postgresql/data
=======
      - ./pgdata:/var/lib/postgresql
>>>>>>> aa1c5d7c8915e2ead1701b5739a6dfc8116113cf
=======
      - ./pgdata:/var/lib/postgresql

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
>>>>>>> e8eb97ff05622b90f384c5fbc829e82218ca52c7

# se jรก existir volumes: mantenha e acrescente pgdata:
volumes:
<<<<<<< HEAD
  pgdata:
=======
  postgres_data:
  redis_data:
>>>>>>> e8eb97ff05622b90f384c5fbc829e82218ca52c7
