services:
  db:
<<<<<<< HEAD
    image: postgres:15
=======
    image: postgres:17
    restart: unless-stopped
>>>>>>> 17f3c16869bd4d4beeb6dc8065b71d46bcf810df
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: disparador_dev
    ports:
      - "5433:5432"
    volumes:
<<<<<<< HEAD
      - pgdata:/var/lib/postgresql/data
      - ./pgdata:/var/lib/postgresql
      - ./pgdata:/var/lib/postgresql
=======
      - dbdata:/var/lib/postgresql/data
>>>>>>> 17f3c16869bd4d4beeb6dc8065b71d46bcf810df

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:  
      - redis_data:/data

volumes:
<<<<<<< HEAD

  pgdata:
  postgres_data:
=======
  dbdata:
>>>>>>> 17f3c16869bd4d4beeb6dc8065b71d46bcf810df
  redis_data:

