services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: disparador_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pgdata:/var/lib/postgresql
      - ./pgdata:/var/lib/postgresql

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:  
      - redis_data:/data

volumes:

  pgdata:
  postgres_data:
  redis_data:

