version: "3.8"

services:
  db:
    image: postgres:latest
    
    restart: always
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: disparador_test
      
    ports:
 
      - "5433:5432"
      
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: