services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: disparador_dev
    ports:
      - "5433:5432"
    volumes:
<<<<<<< HEAD
      - pgdata:/var/lib/postgresql/data
=======
      - ./pgdata:/var/lib/postgresql
>>>>>>> aa1c5d7c8915e2ead1701b5739a6dfc8116113cf

# se jรก existir volumes: mantenha e acrescente pgdata:
volumes:
  pgdata:
