version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: disparador_test
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: cache_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    container_name: api-nodejs
    build: .
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=America/Sao_Paulo
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - REDIS_URL=${REDIS_URL}
      - PORT=3001

volumes:
  dbdata:
  redis_data: